require("atomic.config.options")
require("atomic.config.settings")
require("atomic.config.lazy")
require("atomic.config.keymaps")
require("atomic.config.auto-cmd")
require("atomic.config.health").check()
